### ISSUE TITLE
monochrome mode

### ISSUE THREAD

**Issue by Silther** [NotSimone/Kobo-Metadata#2]
if you change the parameter after the quality from false to true you can get a monochrome picture.
I wouldn't use it but other people may

**Comment by NotSimone** [comment]
This doesn't work too well with downloading full size covers since Kobo doesn't seem to like having only the monochrome true/false flag included. The only way I can see this working with the full size cover downloading is to first download at full size to determine the original size then requesting again at that size with monochrome on. Or mono-chroming ourselves. Either way, kind of annoying for a bit of a niche case.

If enough people want it, it should be easy enough to do. But tbh I don't really see why anyone would want this.
