### ISSUE TITLE
sometimes fails to grab HiRes Covers 

### ISSUE THREAD

**Issue by Silther** [NotSimone/Kobo-Metadata#3]
I have this book 9781789392074, which has a pretty high resolution on the [website](https://www.kobo.com/de/de/ebook/harry-potter-y-las-reliquias-de-la-muerte-4), but the addon fetches only a  288 x 432 version instead of blob:https://www.kobo.com/7aa03e38-0452-42a4-8d75-ad934537c8a6

**Comment by NotSimone** [comment]
I can't get to your link but tbh it looks like its behaving as expected - by default, the image will get scaled (up or down) to 353x569 (its been a bit since I checked but I believe it maintains aspect ratio and tries to hit the 353 width). In your case, it looks like the cover is getting scaled up.
