### ISSUE TITLE
Multi region mode

### ISSUE THREAD

**Issue by Silther** [NotSimone/Kobo-Metadata#4]
I don't know if it's possible, but to select your favourite 3 regions would be pretty nice, because some regions fail to find the books (even if they are on the website).

**Comment by NotSimone** [comment]
I think its a bit tricky from a UI point, especially since I've recently changed the behaviour of ISBN searching to also perform the normal search too. When do we decide to perform a search on a different region? When there are no matches at all? Or not enough matches? Its definitely something I'll think about and I'll welcome any suggestions as to what heuristic to use to try other regions. Or perhaps when I finally get annoyed enough write a ranking algorithm for the closeness of the match instead of just relying on Kobo's search to do the heavy lifting.

For what its worth, I've found the Australian store to have pretty much everything ;)

**Comment by NotSimone** [comment]
Another idea could be to try different regions until we hit the max number of matches. Although again, this ends up not entirely great because there isn't support for going to the second page of search results right now.
